SOLVENT_DATA = {
    '1,1,1-trichloroethane': {'crosses': 2},
    '1,1,2-trichloroethane': {'crosses': 2},
    '1,2,4-trimethylbenzene': {'crosses': 3},
    '1,2-dibromoethane': {'crosses': 3},
    '1,2-dichloroethane': {'crosses': 4},
    '1,2-ethanediol': {'crosses': 2},
    '1,4-dioxane / dioxane': {'crosses': 5},
    '1-bromo-2-methylpropane': {'crosses': 2},
    '1-bromooctane / bromooctane': {'crosses': 3},
    '1-bromopentane': {'crosses': 2},
    '1-bromopropane': {'crosses': 2},
    '1-butanol / butanol': {'crosses': 4},
    '1-chlorohexane / chlorohexane': {'crosses': 4},
    '1-chloropentane': {'crosses': 2},
    '1-chloropropane': {'crosses': 2},
    '1-decanol / decanol': {'crosses': 4},
    '1-fluorooctane': {'crosses': 4},
    '1-heptanol / heptanol': {'crosses': 4},
    '1-hexanol / hexanol': {'crosses': 4},
    '1-hexene': {'crosses': 2},
    '1-hexyne': {'crosses': 2},
    '1-iodobutane': {'crosses': 2},
    '1-iodohexadecane / hexadecyliodide': {'crosses': 4},
    '1-iodopentane': {'crosses': 2},
    '1-iodopropane': {'crosses': 2},
    '1-nitropropane': {'crosses': 2},
    '1-nonanol / nonanol': {'crosses': 4},
    '1-octanol / octanol': {'crosses': 6},
    '1-pentanol / pentanol': {'crosses': 4},
    '1-pentene': {'crosses': 2},
    '1-propanol / propanol': {'crosses': 4},
    '2,2,2-trifluoroethanol': {'crosses': 2},
    '2,2,4-trimethylpentane / isooctane': {'crosses': 4},
    '2,4-dimethylpentane': {'crosses': 2},
    '2,4-dimethylpyridine': {'crosses': 2},
    '2,6-dimethylpyridine': {'crosses': 4},
    '2-bromopropane': {'crosses': 2},
    '2-butanol / secbutanol': {'crosses': 4},
    '2-chlorobutane': {'crosses': 2},
    '2-heptanone': {'crosses': 2},
    '2-hexanone': {'crosses': 2},
    '2-methoxyethanol / methoxyethanol': {'crosses': 4},
    '2-methyl-1-propanol / isobutanol': {'crosses': 4},
    '2-methyl-2-propanol': {'crosses': 2},
    '2-methylpentane': {'crosses': 2},
    '2-methylpyridine / 2methylpyridine': {'crosses': 4},
    '2-nitropropane': {'crosses': 2},
    '2-octanone': {'crosses': 2},
    '2-pentanone': {'crosses': 2},
    '2-propanol / isopropanol': {'crosses': 4},
    '2-propen-1-ol': {'crosses': 2},
    'e-2-pentene': {'crosses': 2},
    '3-methylpyridine': {'crosses': 2},
    '3-pentanone': {'crosses': 2},
    '4-heptanone': {'crosses': 2},
    '4-methyl-2-pentanone / 4methyl2pentanone': {'crosses': 4},
    '4-methylpyridine': {'crosses': 2},
    '5-nonanone': {'crosses': 2},
    'acetic acid / aceticacid': {'crosses': 4},
    'acetone': {'crosses': 5},
    'acetonitrile / mecn / ch3cn': {'crosses': 6},
    'acetophenone': {'crosses': 4},
    'ammonia': {'crosses': 2},
    'aniline': {'crosses': 6},
    'anisole': {'crosses': 4},
    'benzaldehyde': {'crosses': 5},
    'benzene': {'crosses': 6},
    'benzonitrile': {'crosses': 4},
    'benzyl alcohol / benzylalcohol': {'crosses': 4},
    'bromobenzene': {'crosses': 4},
    'bromoethane': {'crosses': 4},
    'bromoform': {'crosses': 4},
    'butanal': {'crosses': 2},
    'butanoic acid': {'crosses': 2},
    'butanone': {'crosses': 4},
    'butanonitrile': {'crosses': 2},
    'butyl ethanoate / butyl acetate / butylacetate': {'crosses': 4},
    'butylamine': {'crosses': 2},
    'n-butylbenzene / butylbenzene': {'crosses': 4},
    'sec-butylbenzene / secbutylbenzene': {'crosses': 4},
    'tert-butylbenzene / tbutylbenzene': {'crosses': 4},
    'carbon disulfide / carbondisulfide / cs2': {'crosses': 6},
    'carbon tetrachloride / ccl4': {'crosses': 4},
    'chlorobenzene': {'crosses': 4},
    'chloroform / chcl3': {'crosses': 6},
    'a-chlorotoluene': {'crosses': 2},
    'o-chlorotoluene': {'crosses': 2},
    'conductor': {'crosses': 2},
    'm-cresol / mcresol': {'crosses': 4},
    'o-cresol': {'crosses': 2},
    'cyclohexane': {'crosses': 4},
    'cyclohexanone': {'crosses': 4},
    'cyclopentane': {'crosses': 2},
    'cyclopentanol': {'crosses': 2},
    'cyclopentanone': {'crosses': 2},
    'decalin': {'crosses': 4},
    'cis-decalin': {'crosses': 2},
    'n-decane / decane': {'crosses': 4},
    'dibromomethane': {'crosses': 3},
    'dibutylether': {'crosses': 4},
    'o-dichlorobenzene / odichlorobenzene': {'crosses': 4},
    'e-1,2-dichloroethene': {'crosses': 2},
    'z-1,2-dichloroethene': {'crosses': 2},
    'dichloromethane / ch2cl2 / dcm': {'crosses': 6},
    'diethyl ether / diethylether': {'crosses': 6},
    'diethyl sulfide': {'crosses': 2},
    'diethylamine': {'crosses': 2},
    'diiodomethane': {'crosses': 2},
    'diisopropyl ether / diisopropylether': {'crosses': 4},
    'cis-1,2-dimethylcyclohexane': {'crosses': 2},
    'dimethyl disulfide': {'crosses': 2},
    'n,n-dimethylacetamide / dimethylacetamide': {'crosses': 4},
    'n,n-dimethylformamide / dimethylformamide / dmf': {'crosses': 6},
    'dimethylsulfoxide / dmso': {'crosses': 6},
    'diphenylether': {'crosses': 4},
    'dipropylamine': {'crosses': 2},
    'n-dodecane / dodecane': {'crosses': 4},
    'ethanethiol': {'crosses': 2},
    'ethanol': {'crosses': 6},
    'ethyl acetate / ethylacetate / ethanoate': {'crosses': 6},
    'ethyl methanoate': {'crosses': 2},
    'ethyl phenyl ether / ethoxybenzene': {'crosses': 4},
    'ethylbenzene': {'crosses': 4},
    'fluorobenzene': {'crosses': 4},
    'formamide': {'crosses': 2},
    'formic acid': {'crosses': 2},
    'furan / furane': {'crosses': 3},
    'n-heptane / heptane': {'crosses': 4},
    'n-hexadecane / hexadecane': {'crosses': 6},
    'n-hexane / hexane': {'crosses': 6},
    'hexanoic acid': {'crosses': 2},
    'iodobenzene': {'crosses': 4},
    'iodoethane': {'crosses': 2},
    'iodomethane': {'crosses': 2},
    'isopropylbenzene': {'crosses': 4},
    'p-isopropyltoluene / isopropyltoluene': {'crosses': 3},
    'mesitylene': {'crosses': 4},
    'methanol': {'crosses': 6},
    'methyl benzoate': {'crosses': 2},
    'methyl butanoate': {'crosses': 2},
    'methyl ethanoate': {'crosses': 2},
    'methyl methanoate': {'crosses': 2},
    'methyl propanoate': {'crosses': 2},
    'n-methylaniline': {'crosses': 2},
    'methylcyclohexane': {'crosses': 2},
    'n-methylformamide / methylformamide': {'crosses': 4},
    'nitrobenzene / phno2': {'crosses': 4},
    'nitroethane': {'crosses': 4},
    'nitromethane / meno2': {'crosses': 6},
    'o-nitrotoluene / onitrotoluene': {'crosses': 3},
    'n-nonane / nonane': {'crosses': 4},
    'n-octane / octane': {'crosses': 4},
    'n-pentadecane / pentadecane': {'crosses': 4},
    'octanol(wet) / wetoctanol / woctanol': {'crosses': 2},
    'pentanal': {'crosses': 2},
    'n-pentane / pentane': {'crosses': 4},
    'pentanoic acid': {'crosses': 2},
    'pentyl ethanoate': {'crosses': 2},
    'pentylamine': {'crosses': 2},
    'perfluorobenzene / hexafluorobenzene': {'crosses': 4},
    'phenol': {'crosses': 4},
    'propanal': {'crosses': 2},
    'propanoic acid': {'crosses': 2},
    'propanonitrile': {'crosses': 2},
    'propyl ethanoate': {'crosses': 2},
    'propylamine': {'crosses': 2},
    'pyridine': {'crosses': 4},
    'tetrachloroethene / c2cl4': {'crosses': 4},
    'tetrahydrofuran / thf': {'crosses': 6},
    'tetrahydrothiophene-s,s-dioxide / tetrahydrothiophenedioxide / sulfolane': {'crosses': 6},
    'tetralin': {'crosses': 4},
    'thiophene': {'crosses': 2},
    'thiophenol': {'crosses': 2},
    'toluene': {'crosses': 6},
    'trans-decalin': {'crosses': 2},
    'tributylphosphate': {'crosses': 4},
    'trichloroethene': {'crosses': 2},
    'triethylamine': {'crosses': 4},
    'n-undecane / undecane': {'crosses': 4},
    'water / h2o': {'crosses': 6},
    'xylene': {'crosses': 3},
    'm-xylene': {'crosses': 2},
    'o-xylene': {'crosses': 2},
    'p-xylene': {'crosses': 2},
}
